services:
  db:
    image: postgres:15-alpine
    container_name: database
    networks:
      - back-net
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: thrall
      POSTGRES_PASSWORD: motherload123

  app:
    container_name: flask
    build:
      context: ./app/
    ports:
      - 5000:5000
    networks:
      - back-net
    environment:
      POSTGRES_DB: flask_db
      POSTGRES_USER: thrall
      POSTGRES_PASSWORD: motherload123
      DB_HOST: db
    depends_on:
      - db

networks:
  back-net:

volumes:
  db_volume:
